//
// Created by jchiu342 on 12/30/21.
//

#ifndef ROOST_MCTS_DEFS_H
#define ROOST_MCTS_DEFS_H

#define DIRICHLET_ALPHA 0.15
#define DIRICHLET_EPSILON_TRAIN 0.25
#define DIRICHLET_EPSILON_VAL 0.1
#define MCTS_CPUCT 1.1
#define PCR_P 0.25
#define TEMP_0_MOVE_NUM_TRAIN 20
#define TEMP_0_MOVE_NUM_VAL 16

#endif // ROOST_MCTS_DEFS_H
